# Generated by Django 4.0.6 on 2022-08-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=15)),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(choices=[('W', 'Withdrawal'), ('S', 'Savings'), ('D', 'Deposits')], max_length=1)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15, null=True)),
                ('age', models.PositiveBigIntegerField()),
                ('id_number', models.CharField(max_length=15, null=True)),
                ('nationality', models.CharField(max_length=15, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=8)),
                ('receipt_date', models.DateTimeField()),
                ('receipt_file', models.FileField(upload_to='')),
                ('total_amount', models.IntegerField()),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=15)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_number', models.ImageField(upload_to='')),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('transaction_fee', models.IntegerField()),
                ('transaction_time', models.DateField()),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_destination', to='wallet.account')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_origin', to='wallet.account')),
                ('transaction_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_transaction_receipt', to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('history', models.DateTimeField()),
                ('pin', models.CharField(max_length=15)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet'),
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=15)),
                ('party_id', models.PositiveSmallIntegerField()),
                ('phone_number', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_account', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reward_points', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='wallet.transaction'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=15)),
                ('notification_date', models.DateTimeField()),
                ('notification_time', models.DateTimeField()),
                ('notification_status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], max_length=1)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField()),
                ('loan_type', models.CharField(max_length=1)),
                ('loan_amount', models.IntegerField()),
                ('loan_date', models.DateTimeField()),
                ('interest_rate', models.IntegerField()),
                ('loan_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('loan_guaranter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_loan', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=15)),
                ('card_number', models.IntegerField()),
                ('card_type', models.CharField(choices=[('C', 'Credit card'), ('D', 'Debit card')], max_length=1)),
                ('cvv_code', models.IntegerField()),
                ('card_issuer', models.CharField(choices=[('V', 'Visa'), ('M', 'Master card')], max_length=1)),
                ('date_issued', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('card_status', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_wallet', to='wallet.wallet'),
        ),
    ]
