# Generated by Django 4.0.6 on 2022-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_transaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('W', 'Withdrawal'), ('S', 'Savings'), ('D', 'Deposits')], max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_issuer',
            field=models.CharField(choices=[('V', 'Visa'), ('M', 'Master card')], max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('C', 'Credit card'), ('D', 'Debit card')], max_length=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='customer_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='party_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
