# Generated by Django 4.0.6 on 2022-08-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_date',
            new_name='notification_date_time',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notification_time',
        ),
    ]
